# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: myvm

steps:
- task: Npm@1
  inputs:
    command: 'install'
    customRegistry: 'useFeed'
    customFeed: 'b5b2b127-52e2-4b2f-b5ef-2e7a4b2b328d'
